#!/bin/bash
# Adjusts the mouse pointer's wonky sensitivity. 

xinput --set-prop pointer:"Sun Sonny USB Gaming Mouse" "Device Accel Constant Deceleration" 2
xinput --set-prop pointer:"Sun Sonny USB Gaming Mouse" "Device Accel Velocity Scaling" 1

echo "SUCCESS: Pointer speed adjusted."
